### ISSUE TITLE
加強購物車頁面

### ISSUE THREAD

**Issue by creek0810** [creek0810/loveat2#53]
- 在不能營業的時間下單後，彈出框除了顯示在非營業時間下單外，還能顯示營業時間，幫助使用者修改下單時間
-  備註也能有記錄功能，使用者回菜單頁面加入新的產品後，回來還能保留看到原本的備註

**Comment by muyumiya1201** [comment]
- [ ] 在不能營業的時間下單後，彈出框除了顯示在非營業時間下單外，還能顯示營業時間，幫助使用者修改下單時間
- [ ] 備註也能有記錄功能，使用者回菜單頁面加入新的產品後，回來還能保留看到原本的備註
